services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: yourjob
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: yourjob_backend
    restart: always
    env_file:
      - ./simple.env
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    depends_on:
      - db

volumes:
  postgres_data: